### ISSUE TITLE
Need a suggestion

### ISSUE THREAD

**Issue by abhishekthanvi8** [robertmryan/BackgroundLocation#1]
Hi Rob 

you added a below warning in you code 

  // warning: You really should not ask for “always” immediately after granting “when in use”,
 // but rather defer this to a place in your app where the utility of “always” is really needed.
  // I'm doing it here just to illustrate the “first ask for ‘when in use’, ask for ‘always’ later”.
  
  
  My issue is I have my first view controller where I am asking for whenInUse permission but in next view controller where I actually want to ask for Always allow it is not showing any always allow alert. But if I ask immediately for always allow after asking for whenInUse it is working fine as in your code.?? 
  
  I have read about provisional always allow thing but in my case how do it get it worked out ? Even the auth satuts I am receving is Always allow but the actual permission is set to whenInUse in settings. ?
  
Thanks. !

**Comment by robertmryan** [comment]
You said:

> My issue is I have my first view controller where I am asking for whenInUse permission but in next view controller where I actually want to ask for Always allow it is not showing any always allow alert. But if I ask immediately for always allow after asking for whenInUse it is working fine as in your code.??

Re failure to see the second alert when you first asked for “when in use” in one view controller, and “always” in the next, I cannot answer that question without a reproducible example.

The only thing I can say is that more than once I have accidentally asked for permission in `viewDidLoad`, which is too early in the process. (You should never initiate the presentation of system alerts (or any UI) in `viewDidLoad`, as the UI is in an intermediate state, likely in the process of presenting the view controller in question.) It should be done in `viewDidAppear` or later.

> I have read about provisional always allow thing but in my case how do it get it worked out ? Even the auth satuts I am receving is Always allow but the actual permission is set to whenInUse in settings. ?

Yeah, it is very confusing, because when you ask for “always” and (unbeknownst to the app) only are granted “provisional always”, the `authorizationStatus` property confusing reports `.always` even though it really is provisional. (They really should have introduced a new `.provisionalAlways` status, but I understand why they didn’t, as that would likely break tons of existing code. At the least they should have added a new `isProvisional` property, or the like. But, alas, they didn’t.) 

What is reported in Settings app more accurately reflects the actual status.

**Comment by abhishekthanvi8** [comment]
Ok I got it. Thanks.
